# oracle jdk 1.8 备用
#FROM runcare/debian-jre1.8

# openjdk 1.8
FROM runcare/openjdk-jre1.8

# 更新版本1
MAINTAINER lucatest917@gmail.com

ARG JMETER_VERSION="5.4.1"
ENV JMETER_HOME /opt/apache-jmeter-$JMETER_VERSION
ENV SSL_DISABLED true


RUN mkdir -p /tmp/dependencies
COPY apache-jmeter-$JMETER_VERSION.tgz /tmp/dependencies/
RUN mkdir -p /opt \
    && tar -xzf /tmp/dependencies/apache-jmeter-$JMETER_VERSION.tgz -C /opt  \
    && rm -rf /tmp/dependencies


# TODO: plugins (later)
# && unzip -oq "/tmp/dependencies/JMeterPlugins-*.zip" -d $JMETER_HOME

# Set global PATH such that "jmeter" command is found
ENV PATH $PATH:$JMETER_HOME/bin

VOLUME ["/data"]

WORKDIR    $JMETER_HOME

RUN sed 's/#server.rmi.ssl.disable=false/server.rmi.ssl.disable=true/g;s/remote_hosts=127.0.0.1/remote_hosts=127.0.0.2:1099/g' ./bin/jmeter.properties > ./bin/jmeter_temp.properties
RUN mv ./bin/jmeter_temp.properties ./bin/jmeter.properties